version: '3.8'

services:
  client:
    image: dingus27/client:latest
    ports:
      - "8081:80"
    depends_on:
      - server

  server:
    image: dingus27/server:latest
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/flask_vue
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flask_vue
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
