pipeline {
  agent any

  environment {
    DOCKERHUB_USERNAME = 'dingus27'
    DOCKERHUB_CREDENTIALS = 'dockerhub'
  }

  stages {
   

    stage('Build Backend') {
      steps {
        dir('server') {
          script {
            docker.build("${DOCKERHUB_USERNAME}/flask-backend:latest")
          }
        }
      }
    }

    stage('Build Frontend') {
      steps {
        dir('client') {
          script {
            docker.build("${DOCKERHUB_USERNAME}/vue-frontend:latest")
          }
        }
      }
    }

    stage('Push to Docker Hub') {
  steps {
    script {
      withEnv(["DOCKER_USER=Dingus27", "DOCKER_PASS=AGaqwzsxedc147852369"]) {
        bat """
          docker login -u %DOCKER_USER% -p %DOCKER_PASS%
          docker push dingus27/flask-backend:latest
          docker push dingus27/vue-frontend:latest
        """
      }
    }
  }
}

    
  }
}
